language: clojure
script: lein doo node "server-tests" once
notifications:
  email:
    on_success: change
    on_failure: change
    recipients:
    - filip@district0x.io
    - juan@district0x.io
    - mike@district0x.io
  slack:
    on_success: always
    on_failure: always
    rooms:
    - district0x:53vhalUfg0MitsQwzjP5PWdd#travis-ci
before_install:
- sudo wget --no-check-certificate -P /bin https://github.com/ethereum/solidity/releases/download/v0.4.24/solc-static-linux
- sudo chmod a+x /bin/solc-static-linux
- sudo ln -s solc-static-linux /usr/bin/solc
before_script:
- lein solc once
- npm install -g ganache-cli
- ganache-cli -p 8549 > /dev/null &
- wget https://dist.ipfs.io/ipfs-update/v1.5.2/ipfs-update_v1.5.2_linux-amd64.tar.gz
  -O ipfs-update.tar.gz
- tar -xzf ipfs-update.tar.gz
- ipfs-update/ipfs-update install latest
- ipfs init
- ipfs daemon > /dev/null &
